name: GoogleTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ make

    - name: Install GoogleTest
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake . 
        sudo make 
        sudo make install

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_CXX_FLAGS="-ffloat-store"


    - name: Build project
      run: |
        cd build
        cmake --build .

    - name: Run tests
      run: |
        cd build/tests
        ctest --verbose --output-on-failure
